### PR TITLE
Requests room estimation without sending building id

### LINKED ISSUE #5: Only send beacon names to server when estimating room
Beacons should no longer be linked to building

### PR DESCRIPTION
**Pull request by sasp1**
Now app just sends the names + rssi to server of whatever beacons it can find. Server takes care of estimating both which building and room user is in. 
Deleted scans for determining which building user is in through beacons. 
Deleted getBeacons request as it is no longer needed. 
I was having some trouble understanding when the global _building object is updated so this might have to be checked. Seems to work fine now, though.

### CODE REVIEW

**Comment by SebastianKotewitz** [comment]
The GlobalState BuildingModel is updated before entering the BuildingManager screen. This is mostly something that was going to be used more in earlier versions of the application, but this can be redone by simply having the BuildingModel data sent to the screen in another way. This would make the GlobalState BuildingModel largely unnecessary I think. I will look into this pull request later and update the BuildingManager accordingly.

**Comment by sasp1** [comment]
Alright, I noticed there were still some errors for the building manager screens since beacons now no longer require uuids. I have fixed that now. But have a look

**Comment by SebastianKotewitz** [comment]
I have now made the building object pass as an argument to the route rather than go through Provider and GlobalState. We can almost entirely remove the Provider and GlobalState systems now, as I don't think its being used for anything anymore.

There are some issues with the new way of storing beacons in the database though. 
Adding multiple beacons is now possible, but adding the same beacons to different buildings is not possible, as they would have the same name.
SignalMaps were also a problem, but that should work after the two commits above.

We can drop adding beacons to buildings in the app entirely if needed. Right now the signalmaps posted when scanning location data for a room is intentionally limited to the beacons registered on the building. When openly scanning for the current room and building, the signalmap is filled with whatever beacons it can currently find.

Also note: The refresh token system is not properly functioning in this version, as it relies on GlobalState instead of SharedPreferences. This should be fixed when we pull the other branch (background-room-estimation).

**Comment by sasp1** [comment]
I think it's fine that you can't add the same beacon to multiple buildings. And if we want to add that functionality in the future, I think the solution is to make the beacon have references to multiple buildings (e.g a list of building ids) instead of having multiple beacons objects representing the same beacon. 

Regarding the refresh token system then maybe it would be a good idea to fix it on this branch before we merge, so we don't have a non-working master. I think it might take some time before we can merge in the background-room-estimation branch. 

Other than that I think the changes looks good!

**Pull request merged**
