### PR TITLE
Refresh token

### PR DESCRIPTION
**Pull request by sasp1**
Implementation of refresh token system. Might need more error handling

### CODE REVIEW

**Comment by sasp1** [comment]
Two requests are sent simultaneously upon startup: /beacons and /feedback. Since jwt is old two calls to /auth/refresh are issued at the same time. Second one gets denied with error "refresh token did not match user".

Generally with refresh token system it is a problem when requests to server are sent in parallel since jwt might be outdated. Solution is probably to make request for new jwt /auth/refresh to be block all other calls. Maybe create a jwt/refresh token manager?

**Comment by SebastianKotewitz** [comment]
There should indeed be some way for the RestService class to automatically handle refreshing the token. As it is now, the token is fetched from the global state every time by simply accessing the field. This can be redone as a function that fetches and overrides the token as necessary. This would be implemented in the globalState.dart or restService.dart, and the function would make sure that the tokens are managed correctly every time it is accessed by the application.

**Comment by SebastianKotewitz** [comment]
I also noticed that tokens were still being referenced in other parts of the application. After the cleanup of RestService, tokens are only managed by the RestService and GlobalState. This made all the other references to "token" and "_token" unused and they have been deleted.

**Comment by SebastianKotewitz** [comment]
I briefly tested the lock by marking the jwt as "expired" every time in the app code. This made the application refresh the token every time and it looks like the 'refresh token did not match user' error is fixed.

**Comment by sasp1** [comment]
This still results in an server response of 400 since upon start the fetch feedback request is actually called before the global state tokens are even set. So the fetch feedback is called without a jwt. I have now updated the unregisteredRoute component with a fetchingTokens state like the already existing _loading state (now renamed to fetchingBeacons). Now the answeredQuestionsWidget is only loaded when tokens are done being fetched (and therefore set in global state). 
I have tested it and it seems to work. But please test this as well! I've put you on "review", so if everything looks good then please mark this PR as OK.

**Comment by SebastianKotewitz** [comment]
I see problems with 401 errors when fetching beacons on my previous code as well, but having the feedback widget wait fixes it. However, the part that made getting the room impossible while already getting the room has been removed, making it possible to spam the search button and have many requests running one after the other. I have simply put this back in and renamed some variables for clarity. I have also moved the fetching of tokens from disk to a step before fetching the room, ensuring that this will only happen the first time they are needed, whereafter they are kept in memory until the app is terminated.

**Comment by SebastianKotewitz** [comment]
It should be working now, but I urge you to look through it first, then we can complete the PR

**Comment by sasp1** [comment]
Ah yes, I figured there was a reason for this check. :) 
Anyway, it looks good now and testing with the server seems to work fine.

**Pull request merged**
